version: "3"
services:
  nginx:
    image: "nginx:latest"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/server-2:/etc/nginx/conf.d
      - ./var/nginx:/var/log/nginx
    restart: always
    logging:
      options:
        max-size: "100m"
